#!/bin/bash

### Arcadia REPL Client
# The ArcadiaReplClient.exe client is written in C#. This script
# finds Unity's Mono VM on the system and uses it to run the client.
# This guarantees consistent behavior across platforms.

### Environment Variable
# ARCADIA_MONO_ROOT - path to Unity's Mono if non-standard

# determine unity mono root
if [ -z "$@" ]
  # no argument, try environment variable or defaults
  then
  if [ -z $ARCADIA_MONO_ROOT ]
    # no environment variable, try defaults
    then
    case `uname` in
      Darwin)
        ARCADIA_MONO_ROOT=/Applications/Unity/Unity.app/Contents/Mono
        ;;
      Linux)
        # TODO almost certainly not enough
        ARCADIA_MONO_ROOT=/opt/Unity/Editor/Data/Mono
        ;;
      *)
        echo "Unknown platform '"`uname`"'."
        echo "We don't know how to find Unity on your system!"
        echo "Try setting the ARCADIA_MONO_ROOT environment variable to the path to Unity's Mono distribution."
        exit
        ;;
    esac
  fi
else
  # use command line
  ARCADIA_MONO_ROOT="$@"  
fi

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-which-directory-it-is-stored-in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MONO_LIBS=$ARCADIA_MONO_ROOT/lib/mono/2.0/
MONO=$ARCADIA_MONO_ROOT/bin/mono

MONO_PATH=$MONO_LIBS $MONO $DIR/Repl.exe
