{unity/Object                arcadia.literals/parse-Object
 unity/GradientAlphaKey      arcadia.literals/parse-GradientAlphaKey
 unity/Bounds                arcadia.literals/parse-Bounds
 unity/Rect                  arcadia.literals/parse-Rect
 unity/Vector2               arcadia.literals/parse-Vector2
 unity/Keyframe              arcadia.literals/parse-Keyframe
 unity/AnimationCurve        arcadia.literals/parse-AnimationCurve
 unity/GradientColorKey      arcadia.literals/parse-GradientColorKey
 unity/NetworkPlayer         arcadia.literals/parse-NetworkPlayer
 unity/LOD                   arcadia.literals/parse-LOD
 unity/MatchTargetWeightMask arcadia.literals/parse-MatchTargetWeightMask
 unity/Vector4               arcadia.literals/parse-Vector4
 unity/Quaternion            arcadia.literals/parse-Quaternion
 unity/Color                 arcadia.literals/parse-Color
 unity/Ray                   arcadia.literals/parse-Ray
 unity/Ray2D                 arcadia.literals/parse-Ray2D
 unity/Plane                 arcadia.literals/parse-Plane
 unity/Color32               arcadia.literals/parse-Color32
 unity/Vector3               arcadia.literals/parse-Vector3}